language: python

before_install:
    - sudo apt-get update
    - sudo apt-get install python-opencv
    - sudo dpkg -L python-opencv

install:
    - pip install --pre -r requirements.txt
    - shovel test.fetch_videos

python:
    - "2.7"

script:
    - shovel test.all_overlaps
