language: python

before_install:
    # opencv
    - sudo apt-get update
    - sudo apt-get install build-essential libgtk2.0-dev libjpeg-dev libtiff4-dev libjasper-dev libopenexr-dev cmake python-dev python-numpy python-tk libtbb-dev libeigen2-dev yasm libfaac-dev libopencore-amrnb-dev libopencore-amrwb-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev libqt4-dev libqt4-opengl-dev sphinx-common texlive-latex-extra libv4l-dev libdc1394-22-dev libavcodec-dev libavformat-dev libswscale-dev
    - cd ~
    - wget https://github.com/Itseez/opencv/archive/2.4.9.tar.gz
    - tar -xvf 2.4.9.tar.gz
    - cd opencv-2.4.9
    - mkdir build
    - cd build
    - cmake -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=ON ..
    - make
    - sudo make install
    - echo "/usr/local/lib" >> /etc/ld.so.conf.d/opencv.conf
    - sudo ldconfig
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig
    # ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - echo -e "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa
    - eval `ssh-agent -s`
    - ssh-add ~/.ssh/id_rsa

install:
    - "pip install --pre -r requirements.txt -q"
    - "python setup.py develop"
    - "shovel test.fetch_videos"

python:
    - "2.7"

notifications:
    email: false
    slack: ic-peopletracking:aEF1UIPlcDEn7NRzu7YEl88H

script:
    - shovel test.all_overlaps

cache:
    directories:
        - $HOME/build
